# Homework 1

To do this assignment, we first import pandas and numpy. The dataset we shall be using to answer the questions is the Car Fuel Efficiency dataset.

In [1]:
import pandas as pd
import numpy as np

## Q1

What version of Pandas did you install?

In [2]:
pd.__version__

'3.0.5'

## Q2

How many records are in the dataset?

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
df.index

RangeIndex(start=0, stop=10000, step=1)

## Q3

How many fuel types are presented in the dataset?

In [6]:
df.fuel_type.nunique()

3

## Q4

How many columns in the dataset have missing values?

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5

What's the maximum fuel efficiency of cars from Asia?

In [8]:
df[df['origin'] == 'Asia'].head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [9]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

## Q6

1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.
   
What did you observe?

In [27]:
df.horsepower.median()

print(f"Median horsepower of cars: {df.horsepower.median()}")

Median horsepower of cars: 254.0

In [29]:
df.horsepower.mode()[0]

print(f"Modal horsepower of cars: {df.horsepower.mode()[0]}")

Modal horsepower of cars: 252.0

In [30]:
df['horsepower'].fillna(df['horsepower'].mode()[0]) #Filling the missing values in the horsepower column with the mode

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [26]:
df['horsepower'].fillna(df['horsepower'].mode()[0]).median()

print(f"Median after filling missing values: {df['horsepower'].fillna(df['horsepower'].mode()[0]).median()}")

Median after filling missing values: 252.0

From the above, we see that the median value *reduced* after replacing the missing values by the mode.

## Q7
1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [33]:
df[df['origin'] == 'Asia'] # A selection of all cars from Asia.

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [35]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']] #Selecting just the vehicle_wight and model_year column

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [37]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7) #Filtering the above to the first 7 entries

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [41]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values # Putting the above in a numpy array
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [42]:
print(X.T)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

In [45]:
XTX = X.T.dot(X)

XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [47]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [48]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [51]:
m = XTX_inv.dot(X.T)
m

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [53]:
w = m.dot(y)

w

array([0.13644777, 0.2327492 ])

In [54]:
print(w[0] + w[1])

0.36919696904925486