In [1]:
import numpy as np

In [2]:
np

## Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n[0, 1]

np.int64(2)

In [17]:
n[0, 1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[0]

array([ 1, 10,  3])

In [19]:
n[2] = [1, 1, 1]
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [20]:
n[:, 1]

array([10,  5,  1])

## Randomly generated arrays

In [21]:
np.random.rand(5, 2)

array([[0.15834594, 0.93484937],
       [0.58259677, 0.25346108],
       [0.81949045, 0.22332699],
       [0.31264277, 0.19580215],
       [0.21061513, 0.95780624]])

In [22]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [23]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [24]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
a + 1

array([1, 2, 3, 4, 5])

In [27]:
a * 2

array([0, 2, 4, 6, 8])

In [28]:
b = (10 + (a * 2))**2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
a > b

array([False, False,  True,  True,  True])

In [32]:
a[a>b]

array([2, 3, 4])

## Summarizing operations

In [33]:
a.min()

np.int64(0)

In [34]:
a.max()

np.int64(4)

In [35]:
a.sum()

np.int64(10)

In [36]:
a.mean()

np.float64(2.0)

In [37]:
a.std()

np.float64(1.4142135623730951)

## Linear Algebra

In [38]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [39]:
u.shape

(4,)

In [40]:
u.shape[0]

4

In [41]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [42]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [43]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [44]:
u.dot(v)

np.int64(14)

### Matrix Vector multiplication

In [45]:
P = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])
P

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [46]:
P.shape

(3, 4)

In [47]:
q = np.array([1, 0.5, 2, 1])
q

array([1. , 0.5, 2. , 1. ])

In [48]:
def matrix_vector_multiplication(P, q):
    assert P.shape[1] == q.shape[0]

    num_rows = P.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(P[i], q)

    return result

In [49]:
matrix_vector_multiplication(P, q)

array([20. ,  6. ,  8.5])

In [50]:
P.dot(q)

array([20. ,  6. ,  8.5])

### Matrix-matrix multiplication

In [51]:
Q = np.array([[1, 1, 2],
              [0, 0.5, 1],
              [0, 2, 1],
              [2, 1, 0]])
Q

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [52]:
def matrix_matrix_multiplication(P, Q):
    assert P.shape[1] == Q.shape[0]

    num_rows = P.shape[0]
    num_cols = Q.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        qi = Q[:, i]
        Pqi = matrix_vector_multiplication(P, qi)

        result[:, i] = Pqi


    return result

In [53]:
matrix_matrix_multiplication(P, Q)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [54]:
P.dot(Q)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### The identity matrix

In [55]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
Q.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix inverse

In [57]:
Qs = Q[[0, 1, 2,]]
Qs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [58]:
Qs_inv = np.linalg.inv(Qs)
Qs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [59]:
Qs_inv.dot(Qs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Introduction to Pandas

In [60]:
import numpy as np
import pandas as pd

#### Dataframes

In [61]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

Now, we can turn it into a dataframe using `DataFrame`constructor. Pandas doesn't know what the columns are, so itt simply numbers them 0, 1, 2, 3, 4. However, we can tell it what each column means with the special parameter `columns`:

In [62]:
df = pd.DataFrame(data, columns = columns)

In [63]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Alternatively, we can use a list of dictionaries to create a dataframe:

In [64]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    # ...
]

In [65]:
pd.DataFrame(data)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

For a very large dataframe, we can read the first few rows by using the `head` method.

In [66]:
df.head(n=3)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

#### Series

In [67]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [68]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [69]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [70]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [71]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

To add a new column we do as follows. Note that the dimensioon of the added column has to match what we already have in our dataframe.

In [72]:
df['id'] = [1, 2, 3, 4, 5]

In [73]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

We can also change the column as follows

In [74]:
df['id'] = [10, 20, 30, 40, 50]

In [75]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

To delete a column, we proceed as follows;

In [76]:
del df['id']

In [77]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Index

In [78]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [79]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

Notice that all the dataframes have the same indices.

In [80]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

We can access the elements of the dataframe using this index

In [81]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [82]:
df.loc[[1, 3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

We may also rename the index, using say alphabets, instead of numbers.

In [83]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [84]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [85]:
df.loc[['b', 'c']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

We still can refer to elements using positional index, we use the `iloc`

In [86]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [87]:
df.iloc[[1, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

We may reset the indices as foollows.

df.reset_index()

Observe that we have both the sequential index and the madeup index. If we wish to drop the  madeup index, we do it as follows.

In [88]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

NB: The above doesn't change the dataframe, it only creates a new dataframe.

In [89]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

To overide it with the new one, we just reassign it.

In [90]:
df = df.reset_index(drop=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Element-wise operations

Just like in numpy, we can do pointwise operations.

In [91]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [92]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

The above is a logical operation to determine cars that were made after the year $2015$

#### Filtering

In [93]:
df[df['Year'] >= 2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

The above gives the table of cars made after $2015$, it basically applies the `df`on the Boolean values. The table below gives the list of Nissan cars.

In [94]:
df[df['Make'] >= 'Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

We can combine this. Say we want to get cars that are manufactured by Nissan and produced after 2015, we use the logical $&$ operator.

In [95]:
df[(df['Make'] >= 'Nissan') & (df['Year'] >= 2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### String operations

Unlike numppy, pandas have  some strings, and below are some ways to manipulate them.

In [96]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

The above has sedan and Sedan, we would like to standardise it. We want to use the string methods on the entire series.

In [97]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [98]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

Observe that although we made everything lowercase, it doesn't override the original table

In [99]:
df['Vehicle_Style'].str.replace(' ', '_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

Now, we can use the assignment operator to replace the vehicle style column in the original table by the above.

In [100]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [101]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

#### Summariziing operations

In [102]:
df.MSRP.max()

np.int64(54990)

In [103]:
df.MSRP.min()

np.int64(2000)

In [104]:
df.MSRP.mean()

np.float64(30186.0)

In [105]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [106]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [108]:
df.describe().round() #To round it up to 1 d.p

         Year  Engine HP  Engine Cylinders     MSRP
count     5.0        4.0               5.0      5.0
mean   2010.0      203.0               4.0  30186.0
std      11.0       51.0               1.0  18985.0
min    1991.0      138.0               4.0   2000.0
25%    2010.0      180.0               4.0  27150.0
50%    2017.0      206.0               4.0  32340.0
75%    2017.0      229.0               4.0  34450.0
max    2017.0      261.0               6.0  54990.0

In [109]:
df.Make.nunique() #To calculate unique values

4

In [110]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

#### Missing values

In [111]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [112]:
df.isnull().sum() #Sums accros columns

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

#### Grouping

```
SELECT
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type

```

df.groupby('Transmission Type').MSRP.max()

#### Getting the Numpy arrays

In [122]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [125]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [127]:
df.to_dict(orient= 'records') #Convert from dataframe to dictionary

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]